### ISSUE TITLE
Generate FMU Menu not updated

### ISSUE THREAD

**Issue by MaximeBaudette** [SmarTS-Lab/iTesla_RaPId#18]
The menu requires to load the values stored in dataFmu.mat to open. 
I suspect it has not been updated as the other menus to use default values if nothing is found in the RaPIdobject. 
BTW: maybe these settings shouldn't be in the RaPIdobject but somewhere else, like store on the user'd machine in a system folder?

**Comment by lvanfretti** [comment]
We did this on a rush with Achour, because iTesla people didn't like to have to generate the FMU...
It only supports Dymola also...
There is no checks for installation of Dymola in the starting script, so the user wouldn't even get a clear message about missing dependency.
We have the following options, to Modify so it supports Jmodelica and OpenModelica in addition to Dymola, or we update for Dymola until iTesla end and then we deprecate it.
I think this feature is unnecessary... users should be able to provide or generate the FMU from their Modelica tool or from somewhere else. I think this feature is for very 'junior' users and I don't think is worth keeping it in the future as it adds more complexity to maintenance...

**Comment by janlav** [comment]
Fix in 21f9a4c which removes the dependency on dataFmu.mat - i will change the label to Not Urgent. Luigis comments for JModelica and OpenModelica support are a feature for the future.

**Comment by MaximeBaudette** [comment]
@janlav 
I think we should just deprecate the function. No need to try to fix something into this toolbox when it's not even it's primary objective.
